server:
  port: 4400
#  context-path: aaa
spring:
  application:
    name: Recovery
  cache:
    type: simple   #指定所使用的缓存管理器
#    cache-names: sampleCache
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册(测试@EnableCache)
  servlet:
    multipart:
      #单个文件大小限制
      maxFileSize: -1
      maxRequestSize: -1
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.109:3306/demo?characterEncoding=utf8&useUnicode=true
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: ymq815129539@qq.com
    password: oizvaxuutqomghfe
    default-encoding: UTF-8
    port: 465
    properties.mail.smtp.ssl.enable: true
  ding:
    url: https://oapi.dingtalk.com/robot/send?access_token=
    token: 8bd0d1a2ae79bf86c29a21bc6b25d2f5b76d833e92fa4dbbd91365eea1e01270

mybatis-plus:
  type-aliases-package: com.example.springBootDemo.entity
  mapper-locations: classpath*:mapper/*.xml
  # Mybatis 开启驼峰标识, 数据库为下划线命名规则, 而实体类为驼峰标识, 不开启此选项无法查询出数据
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
 # 开启增强配置
 enable: true
 # 是否生产环境
 production: false
# 这个会让你写账号密码
# basic:
#   enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    # 该参数是swagger默认的排序规则，如果设置为alpha，那么Knife4j提供的按照order排序的增强规则不生效
    operations-sorter: alpha


#  name:WO
#  profile:E:/uploadPath
#eureka:
#  client:
#    register-with-eureka:false
#    fetch-registry:false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.109:8761/eureka/





