server:
  port: 4400
spring:
  application:
    name: login-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.1.109:3306/demo?characterEncoding=utf8&useUnicode=true
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=GMT&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.example.springBootDemo.domain

#wo：
#  name:WO
#  profile:E:/uploadPath
#eureka:
#  client:
#    register-with-eureka:false
#    fetch-registry:false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.109:8761/eureka/





