server:
  port: 4400
spring:
  application:
    name: login-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.109:3306/demo?characterEncoding=utf8&useUnicode=true
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  type-aliases-package: com.example.springBootDemo.entity
  mapper-locations: classpath*:mapper/*.xml
  # Mybatis 开启驼峰标识, 数据库为下划线命名规则, 而实体类为驼峰标识, 不开启此选项无法查询出数据
  configuration:
    map-underscore-to-camel-case: true


#wo：
#  name:WO
#  profile:E:/uploadPath
#eureka:
#  client:
#    register-with-eureka:false
#    fetch-registry:false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.109:8761/eureka/





